Octavia CLI guide
elastx/elx-docs pull request #109
Opened 2023-02-20 09:55 UTC by evgeluev

2023-03-10 15:49 UTC, herr-hxp requested changes
Some comments made in the md file

2023-03-16 10:32 UTC, evgeluev commented on content/en/docs/openstack-iaas/guides/octavia-cli.md
> +$ openstack keypair create --public-key "my-key.pub" my-key
What do you mean by original file instead of a new one? As it is now, it's using an existing SSH-key and not creating a new one?

2023-03-17 16:00 UTC, herr-hxp commented on content/en/docs/openstack-iaas/guides/octavia-cli.md
> +$ openstack keypair create --public-key "my-key.pub" my-key
Instead of copying the contents of the key file in step 4.1, pasting it in a new file in 4.2 and then pointing to the new file in 4.3 it could point to the original file in, like:
`$ openstack keypair create --public-key "~/.ssh/id_ed25519.pub" my-key`

2023-03-21 10:48 UTC, evgeluev commented on content/en/docs/openstack-iaas/guides/octavia-cli.md
> +http://91.197.42.77/
What do you mean by if this IP will work? If you visit that IP now - you will see that the LB works. But I'm not intending to keep these instances / LB for ever just for the purpose of being "alive" in case someone wants to try out and see if that IP will work. But if you would like to use exact same IP in your project as in this example - then no.

Whatever IP you get during Step 6.2 will work.

2023-03-21 12:30 UTC, evgeluev commented on content/en/docs/openstack-iaas/guides/octavia-cli.md
> +**Step 8.1 Generate a test certificate**
Propably not often. The purpose of this was just to show how a cert could be used in context of the subject.

Doesn't a self-signed cert fit describtion: "..  show how they use a cert of any kind .." ?

2023-11-14 11:45 UTC, testviking commented
https://elastx.slack.com/archives/C05QH9WCCLD/p1699961931590129

2023-11-14 11:57 UTC, Brittlejf commented
I feel like there's too much in this PR that's not necessarily related to the load balancing service here, such as creating a web server, certificates, floating IP's, the confusing load balancer pools for SSH access to individual servers among other things. 
We should probably just refer the customers to the official documentation here instead https://docs.openstack.org/octavia/latest/user/guides/basic-cookbook.html

2023-11-14 11:57 UTC, closed without merging