Update documentation for Kubernetes 1.26+ and PCaaS2
elastx/elx-docs pull request #132
Opened 2023-07-11 13:23 UTC by huxcrux

2023-07-13 13:03 UTC, holmsten requested changes
Found some bits that should be fixed but in general it looks good!

2023-07-13 13:03 UTC, holmsten commented on content/en/docs/private-kubernetes/guides/loadbalancer.md
> +Loadbalancers are by default proxying TCP traffic however can be set to proxy UDP traffic, haproxys proxy protocal and even set to HTTP and HTTPS mode meaning the loadbalancer will act as a reverse p
This section is a bit hard to follow and contain some spelling errors.

2023-07-14 08:39 UTC, holmsten approved these changes

2023-07-18 10:14 UTC, SereneVirus commented on content/en/docs/private-kubernetes/changelog/k8s-1.26.md
> +The deployed Kubernetes version varies based on when your cluster is deployed. We try deploying cluster using the lasted patch release of Kubernetes.
Should probably be "latest" instead of "lasted"

2023-07-18 10:17 UTC, SereneVirus commented on content/en/docs/private-kubernetes/changelog/k8s-1.26.md
> +  * Support for node autoscaling is added
Just an opinion, but it is more common and easier to read with the verb first, i.e:
"Added support for node autoscaling
Added this
Removed this
Implemented that"

2023-07-18 10:19 UTC, SereneVirus commented on content/en/docs/private-kubernetes/changelog/k8s-1.26.md
> +> **Please note:** The following changes does not have a set Kubernetes release. However, the replacement labels are already implemented.
Maybe change to "The replacement labels are however already implemented". Don't want to start a sentence with "However"

2023-07-18 10:21 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/example-deployment.md
> +This page will help you getting an deployment up and running and exposed as a load balancer.
*a deployment

2023-07-18 10:21 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/example-deployment.md
> +You can verify access by running `kubectl get nodes` and if the output is simullar to the example below you are set to go.
*similar

2023-07-18 10:22 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/example-deployment.md
> +1. Start of by creating a file called `deployment.yaml` with the content of the deployment below:
off *

2023-07-18 10:24 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/example-deployment.md
> +After your pods are created we need to make sure to expose our deployment. In this example we are creating a service of type loadbalancer. If you would have run this application on production you mos
A bit messy. Suggestion:
"If you run this application in production you would likely install an [ingress controller](../../guides/install-ingress/)

2023-07-18 10:26 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/recommendations.md
> +> **Note:** You do not need to follow this documentation on order to use your cluster
*in order

2023-07-18 10:26 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/recommendations.md
> +To make it easier to expose a lot of applications an ingress controller is a common to deploy.
Either "is common to deploy" or "is commonly deployed"

2023-07-18 10:27 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/recommendations.md
> +Below we describe requests and limits briefly. However for a more detailed description or help setting requests and limits we recommend to check out Kubernetes documentation: https://kubernetes.io/do
Skip the "However"

2023-07-18 10:29 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/recommendations.md
> +If you are using auto scaling requests also help the scheduler when to add new nodes.
A bit confusing. Is it meant to be "Using auto scaling requests also help"?

2023-07-18 10:30 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/recommendations.md
> +`CPU` limit you application will be throttled or simply run slower when trying to exceed the limit.
Maybe change to `CPU` limit. Your application will be...

2023-07-18 10:31 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/recommendations.md
> +Autoscaling can be done by scaling nodes and or pods. To get the absolute best experience we recommend a combination of both.
*and/or

2023-07-18 10:31 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/recommendations.md
> +We have built in support for the scale nodes up and down. To get started with auto scaling we recommend that you check out our [guide that can be found here](../../guides/autoscaling/)
*for scaling nodes up and down

2023-07-18 10:33 UTC, SereneVirus commented on content/en/docs/private-kubernetes/getting-started/recommendations.md
> +Network policy can be used to limit both incoming and outgoing traffic. This allows you to for example specify that only a set of your pods are allowed to talk to the database.
This allows you for example to*

2023-07-18 10:35 UTC, SereneVirus commented on content/en/docs/private-kubernetes/guides/autoscaling.md
> +If you are unshare contact out support and we will help you get the configuration you wish for.
*unsure

2023-07-18 10:37 UTC, SereneVirus commented on content/en/docs/private-kubernetes/guides/autoscaling.md
> +Nodes are added once they are needed. and there is 2 scenarious.
Nodes are added once they are needed and there are 2 scenarios:*

2023-07-18 10:45 UTC, SereneVirus commented on content/en/docs/private-kubernetes/guides/autoscaling.md
> +2. You schedule pods with requests and the autoscaler senses that your pods won't be able to be scheduled. If a lot of pods are schedule this method can add more than one node at a time.
Second sentence should probably be *scheduled

2023-07-18 10:46 UTC, SereneVirus commented on content/en/docs/private-kubernetes/guides/ingress-prep-pre-126.md
> +We run ingress controllers as daemonsets on each of the worker nodes. Providing a
*This provides
*into your cluster

2023-07-18 10:47 UTC, SereneVirus commented on content/en/docs/private-kubernetes/guides/ingress-prep-pre-126.md
> +We deliver our clusters unaccessible from the internet, to provide ingress
*inaccessible

*from the internet. To provide

2023-07-18 10:47 UTC, SereneVirus commented on content/en/docs/private-kubernetes/guides/ingress-prep-pre-126.md
> +To do so, log in to [Elastx OpenStack IaaS](https://ops.elastx.cloud/). Once logged
*into

2023-07-18 10:49 UTC, SereneVirus commented on content/en/docs/private-kubernetes/guides/ingress.md
> +For cluster running Kubernetes 1.26 or later we will publish a guide on how to install and upgrade your ingress and cert-manager deployments
Maybe add "... how to install and upgrade your ingress and cert-manager deployments yourselves" at the end to clarify this is something the customer will have to do moving forward.

2023-07-18 10:50 UTC, SereneVirus commented on content/en/docs/private-kubernetes/guides/loadbalancer.md
> +Loadbalancers have support for multiple protocols. In general we would recommend everyone to try avoiding http and https due to a few limitations and simply they does not perfom as well as other prot
*simply because they do not perform

2023-07-18 10:54 UTC, SereneVirus commented on content/en/docs/private-kubernetes/guides/ingress.md
> +For cluster running Kubernetes 1.26 or later we will publish a guide on how to install and upgrade your ingress and cert-manager deployments
This was also covered in content/en/docs/private-kubernetes/overview.md
Maybe point the documentation to the PCaaS overview instead of having almost the same information written twice.

2023-07-18 10:55 UTC, SereneVirus commented on content/en/docs/private-kubernetes/overview.md
> +If you are ordering a new Kubernetes cluster you need to install an ingress and certmanager on your own behalf. We have however created a guide on how to install Nginx Ingress Controller and cert-man
*coming

2023-07-18 10:56 UTC, SereneVirus requested changes
Since this is customer facing I have made many grammatical suggestions and corrected some errors throughout comments.

2023-07-18 12:43 UTC, huxcrux commented on content/en/docs/private-kubernetes/guides/ingress.md
> +For cluster running Kubernetes 1.26 or later we will publish a guide on how to install and upgrade your ingress and cert-manager deployments
I think it could be a good thing to have both here and the ovewrview page for now. The overview page will most likely get cleaned up as soon as all clusters are upgraded to 1.26 or later

2023-07-18 12:49 UTC, huxcrux commented on content/en/docs/private-kubernetes/getting-started/recommendations.md
> +If you are using auto scaling requests also help the scheduler when to add new nodes.
Reprashed this sentence, is ot more clear now?

2023-07-18 12:57 UTC, SereneVirus approved these changes

2023-07-18 12:58 UTC, SereneVirus approved these changes
Looking good now!

2023-10-20 09:47 UTC, zrk02 commented on content/en/docs/private-kubernetes/guides/autoscaling.md
> +In order to activate auto scaling we need to know `clustername` and `nodegroup` with two values for `minimum/maximum` number of desired nodes. Currently we cannot have minimum set below 3 nodes howev
```suggestion
In order to activate auto scaling we need to know `clustername` and `nodegroup` with two values for `minimum/maximum` number of desired nodes. Currently we have a minimum set to 3 nodes however this is subject to change in the future.
```

2023-10-23 12:38 UTC, merged