Added additional info about storage capacity and backup restores
elastx/elx-docs pull request #137
Opened 2023-09-20 12:17 UTC by mijanss

2023-09-20 15:07 UTC, testviking commented
Should we add something like:

Please remember that the database becomes read-only when 90% or more of the disk space is used.

2023-09-22 08:11 UTC, testviking commented
closes elastx/issue-tracker/issues/202

2023-09-22 09:01 UTC, Tipset requested changes
Do the proposed changes from @testviking before pushing.

2023-09-22 09:13 UTC, Tipset approved these changes
This looks better.

2023-09-22 09:28 UTC, testviking commented
I added two more reviews.

2023-09-22 09:29 UTC, testviking commented
With my permission level in this repo, all my reviews get stuck as Pending and I cannot resolve them myself. So please keep this in mind.

2023-09-22 09:53 UTC, testviking reviewed
Please see my comments.

2023-09-22 09:53 UTC, testviking commented on content/en/docs/dbaas/getting-started/DBaaS-guides.md
>  #### Backup copy temporarily stored on the node
This limitation has been fixed by S9S and can be removed from here.

2023-09-22 09:53 UTC, testviking commented on content/en/docs/dbaas/getting-started/DBaaS-guides.md
> +When you wish to restore a datastore from backup, you need to ensure that your storage usage on each datastore node is at maximum 65%. This is because the current restore from backup method will use
The text seems to be clear now. I cannot resolve this. Someone else will need to resolve it.

2023-09-22 09:53 UTC, testviking commented on content/en/docs/dbaas/getting-started/DBaaS-guides.md
> +#### Restore from backup and available storage capacity
Maybe the heading should be something more like:

Before you restore from backup: storage usage must be max 65%

2023-09-22 09:56 UTC, testviking commented on content/en/docs/dbaas/getting-started/DBaaS-guides.md
> +When you wish to restore a datastore from backup, you need to ensure that your storage usage on each datastore node is at maximum 65%. This is because the current restore from backup method will use
I am fine with leaving it at 65%. I don't know if we need to ever think about these details.

2023-09-22 09:59 UTC, testviking commented
My bad. I started a review now. It has been a while, so I forgot that I need to start a review.

2023-09-22 11:57 UTC, mijanss commented on content/en/docs/dbaas/getting-started/DBaaS-guides.md
>  #### Backup copy temporarily stored on the node
Fixed limitation removed.

2023-09-22 11:58 UTC, mijanss commented on content/en/docs/dbaas/getting-started/DBaaS-guides.md
> +#### Restore from backup and available storage capacity
Changed the heading.

2023-09-22 12:01 UTC, mijanss commented on content/en/docs/dbaas/getting-started/DBaaS-guides.md
> +When you wish to restore a datastore from backup, you need to ensure that your storage usage on each datastore node is at maximum 65%. This is because the current restore from backup method will use
Thank you @testviking  for the detailed clarification.
I agree that 65% could be kept.

2023-09-22 12:01 UTC, testviking approved these changes
Thank you. Looks good.

2023-09-22 12:16 UTC, Tipset commented on content/en/docs/dbaas/getting-started/DBaaS-guides.md
> +When you wish to restore a datastore from backup, you need to ensure that your storage usage on each datastore node is at maximum 65%. This is because the current restore from backup method will use
nice @testviking , I suppose this is now resolved.

2023-09-22 12:19 UTC, merged