Mijanss/update dbaas docs
elastx/elx-docs pull request #185
Opened 2024-05-28 10:34 UTC by mijanss

Update dbaas documentation.

2024-05-28 13:21 UTC, nyxi reviewed
I also see we are not consistent in how we are highlighting words/phrases, in some places we use inline code snippets, in others cursive, in others bold. Would look better if we chose one method and stuck to it.

2024-05-28 13:21 UTC, nyxi commented on content/en/docs/dbaas/dbaas-getting-started.md
> +    **Volume storage option:** This is the *recommended* storage alternative for most setups. With volume storage you have the ability to choose your own storage size and type. Minimum size requireme
"for most setups", either remove this or give an example of when it is not recommended

2024-05-28 13:42 UTC, mijanss commented on content/en/docs/dbaas/dbaas-getting-started.md
> +    **Volume storage option:** This is the *recommended* storage alternative for most setups. With volume storage you have the ability to choose your own storage size and type. Minimum size requireme
@nyxi Thank you for the feedback. I've a suggestion to move the difference between ephemeral and volumes to its own paragraph. That way it can also be more easily linked to from other parts of the documentation. What do you think?

I'll check the bold/cursive/inline inconsistency.

2024-05-29 10:17 UTC, nyxi requested changes

2024-05-29 10:17 UTC, nyxi commented on content/en/docs/dbaas/dbaas-getting-started.md
> +*  Ephemeral storage option: This is the ephemeral storage that is included in your selected flavor. It has a static size as shown on the flavor and cannot be resized. It is the fastest storage type
I would probably go with something more simple here, something along the lines of:

> Volumes are resilient and resizable. Ephemeral storage is neither resilient nor resizable, but has the best performance. We recommend volumes. Ephemeral storage is only a good idea if you need the best performance and can be certain your database won't grow much in size.

2024-05-29 12:10 UTC, mijanss commented on content/en/docs/dbaas/dbaas-getting-started.md
> +*  Ephemeral storage option: This is the ephemeral storage that is included in your selected flavor. It has a static size as shown on the flavor and cannot be resized. It is the fastest storage type
Keeping it simple and informative sounds good, then a separate paragraph is probably not needed. Moving information back to the storage selection step. Thanks

2024-05-30 07:29 UTC, klasahl commented on content/en/docs/dbaas/guides/_index.md
> +weight: 3
Bra!

2024-05-30 07:29 UTC, klasahl approved these changes
Snyggt!!!!!!!

2024-05-30 08:42 UTC, merged