DBaas changelog v1.50
elastx/elx-docs pull request #215
Opened 2024-12-10 15:57 UTC by klasahl

Added changes and bugfixes for CCX v 1.50.

2024-12-16 08:06 UTC, klasahl commented
@mijanss Can you take a look?

2024-12-18 10:05 UTC, klasahl reviewed
@mijanss  Made changes to the TLS parts. Do you think this is better?

2024-12-19 07:38 UTC, mijanss requested changes
@klasahl I think it looks good.

Only one change regarding postgres 16.

2024-12-19 07:38 UTC, mijanss commented on content/en/docs/dbaas/changelog/_index.md
> +* Postgres 16.
This is not in place yet

2025-01-14 13:56 UTC, mijanss approved these changes
LGTM

2025-01-14 13:59 UTC, merged