Create getting_started
elastx/elx-docs pull request #45
Opened 2022-01-31 08:34 UTC by zrkelastx

Migration of:
https://elastx.zendesk.com/knowledge/articles/218042523/en-us?brand_id=2236496

2022-01-31 08:39 UTC, Doctor-love commented on content/en/docs/openstack-iaas/guides/getting_started
> +If you used any other image you can find the default user names here https://elastx.zendesk.com/hc/en-us/articles/214237986-How-to-log-in-to-your-new-Linux-instance
Maybe we could migrate this page from the support portal as well (as it's a dependency) in the same PR?

2022-01-31 08:40 UTC, Doctor-love commented on content/en/docs/openstack-iaas/guides/getting_started
> +
Some redundant empty lines

2022-01-31 08:49 UTC, Doctor-love commented
@zrkelastx : If you run "test-locally.sh" and check out the formatting of the guide, you'll notice that the syntax in the TODO steps don't quite render as you expect.

2022-01-31 12:31 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/getting_started
> +If you used any other image you can find the default user names here https://elastx.zendesk.com/hc/en-us/articles/214237986-How-to-log-in-to-your-new-Linux-instance
yes, I will include it.

2022-01-31 12:42 UTC, zrkelastx commented
> @zrkelastx : If you run "test-locally.sh" and check out the formatting of the guide, you'll notice that the syntax in the TODO steps don't quite render as you expect.

thnx, attempted it during last commit.ttt

2022-01-31 15:55 UTC, Doctor-love requested changes

2022-01-31 15:55 UTC, Doctor-love commented on content/en/docs/openstack-iaas/guides/getting_started.md
> +When using Heat to deploy instances the user name will be ec2-user instead.
Perhaps consider using the table syntax instead? Example:
```
| Property | Value |
|-------------|------------------------------------|
| Server    | smtp.elastx.email
| Port        | 587
| Protocol | SMTP + STARTTLS (preferred)
```

In markdown, if you want to force a newline, you'll have to end each line with two spaces.

2022-01-31 15:55 UTC, Doctor-love commented on content/en/docs/openstack-iaas/guides/getting_started.md
> +1. set instance name > "Next"
Fix casing for items.

2022-01-31 15:55 UTC, Doctor-love commented on content/en/docs/openstack-iaas/guides/getting_started.md
> +1. select "Image" in"Select Boot Source" >  select "No" in "Create New Volume"
Add lacking space

2022-01-31 15:57 UTC, Doctor-love commented on content/en/docs/openstack-iaas/guides/getting_started.md
> +2. Select "Create Router" > set a router name and select the public network "ext-net-01" > "Create Router"
Isn't this called "elx-public1" these days?

2022-02-01 08:27 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/getting_started.md
> +When using Heat to deploy instances the user name will be ec2-user instead.
Good idea.

2022-02-01 08:31 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/getting_started.md
> +1. set instance name > "Next"
Fixed loads of casing.

2022-02-01 09:08 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/getting_started.md
> +When using Heat to deploy instances the user name will be ec2-user instead.
fixxed.

2022-02-01 09:09 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/getting_started.md
> +2. Select "Create Router" > set a router name and select the public network "ext-net-01" > "Create Router"
Nice catch, fixxed too.

2022-02-01 09:12 UTC, Doctor-love requested changes
Soon ready for merge - except small spelling issue and the public network name!

2022-02-01 09:12 UTC, Doctor-love commented on content/en/docs/openstack-iaas/guides/getting_started.md
> +Thiis is the generic pattern to login from a Linux client:
"Thiis" -> "This"

2022-02-01 09:33 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/getting_started.md
> +Thiis is the generic pattern to login from a Linux client:
iiiiii will handle this one too :))

(sorry about the elx-public1 - that is done on both line 20 and 51 now.)

Thank you for your patience.

2022-02-01 09:39 UTC, Doctor-love approved these changes
Good job!

2022-02-01 10:29 UTC, merged