adding affinity guide
elastx/elx-docs pull request #46
Opened 2022-02-01 14:04 UTC by zrkelastx

Migration of:
https://elastx.zendesk.com/knowledge/articles/214238046/en-us?brand_id=2236496

Adapted and tested commands, as the policy instruction seemed legacy and did not work.

Last command of setting up a VM is not fully tested, but is also not particularly verbose in initial version.

2022-02-01 14:13 UTC, jaanvaks requested changes
Looks good but some minor changes

2022-02-01 14:13 UTC, jaanvaks commented on content/en/docs/openstack-iaas/guides/affinity.md
> +---
Please add new line between 6&7

2022-02-01 14:13 UTC, jaanvaks commented on content/en/docs/openstack-iaas/guides/affinity.md
> +This is a guide on how to make sure the a group of instances do not run on the same compute node. For example if you want to run a cluster of instances you do not want multiple instances to fail if a
Remove the 'a' that shouldn't be there.

2022-02-01 14:32 UTC, bl0m1 reviewed
As discussed on slack I have added examples to use the Openstack cli instead. Also updated image/flavor in the instance creation command.

Also in all comments I have linked to the openstack documentation where the relevant command together with all options can be found :)

2022-02-02 08:57 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/affinity.md
> +---
confirmed.

2022-02-02 08:57 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/affinity.md
> +This is a guide on how to make sure the a group of instances do not run on the same compute node. For example if you want to run a cluster of instances you do not want multiple instances to fail if a
check.

2022-02-02 09:05 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/affinity.md
> +```nova server-group-create testgroup anti-affinity```
I updated the commands as suggested. 

In the links, I see you reference the 'pike' version.
Would it be more fitting to use our upcoming 'train' version ?
https://docs.openstack.org/python-openstackclient/train/cli/command-objects/server.html
To the naked eye, they look really similar.

2022-02-02 09:06 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/affinity.md
> +```nova server-group-list | grep -Ei "Policies|affinity"```
updated command.

2022-02-02 09:13 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/affinity.md
> +```nova server-group-create testgroup anti-affinity```
accidentially pasted wrong link; 
https://docs.openstack.org/python-openstackclient/train/cli/command-objects/server-group.html

2022-02-02 09:16 UTC, bl0m1 commented on content/en/docs/openstack-iaas/guides/affinity.md
> +```nova server-group-create testgroup anti-affinity```
Openstack commands rarely changes. All commands in this pr are the same even in the latest release of Openstack (Xena)

2022-02-02 09:19 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/affinity.md
> +```nova boot --image IMAGE_ID --flavor m1.small --hint group=SERVER_GROUP_UUID cluster-node-1 ```
updated.

2022-02-02 09:20 UTC, zrkelastx commented on content/en/docs/openstack-iaas/guides/affinity.md
> +```nova server-group-create testgroup anti-affinity```
excellent.

2022-02-09 11:13 UTC, Doctor-love commented on content/en/docs/openstack-iaas/guides/affinity.md
> +Info: https://docs.openstack.org/python-openstackclient/train/cli/command-objects/server.html
Mayhaps we should match these links to our current version of OpenStack?
Also add list formatting?

2022-02-14 12:35 UTC, jaanvaks approved these changes
LGTM
I haven't tested the commands though

2022-03-17 12:03 UTC, zrkelastx commented
This long lost PR received some love again.
Reworked according to suggestions.

Hopefully this is good to go now.

2022-03-17 12:34 UTC, MrMoreau approved these changes
LGTM!

2022-03-17 13:59 UTC, merged