Evgeluev/jel nginx load balancer redirect
elastx/elx-docs pull request #72
Opened 2022-03-15 10:11 UTC by evgeluev

2022-03-16 07:59 UTC, Doctor-love requested changes

2022-03-16 07:59 UTC, Doctor-love commented on content/en/docs/jelastic-paas/guides/nginx_restrict_access.md
> +title: "Nginx access restriction"
There already exist a PR for this guide: #56

2022-03-16 07:59 UTC, Doctor-love commented on content/en/docs/jelastic-paas/guides/nginx_load_balancer_redirect.md
> +title: "Nginx Load Balancer Redirect"
Maybe something like "Nginx HTTP to HTTPS redirect

2022-03-16 09:49 UTC, MrMoreau reviewed
+1 on changing the title, otherwise it LGTM

2022-03-17 09:27 UTC, Doctor-love approved these changes
Let's get this merged!

2022-03-17 09:36 UTC, merged